spring.application.name=myvisionboard

server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.datasource.url=jdbc:postgresql://localhost:5432/myvisionboard
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.tags-sorter=alpha
springdoc.writer-with-default-pretty-printer=true
springdoc.swagger-ui.disable-swagger-default-url=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=myvisionboard-secret-key-troque-por-uma-chave-segura
jwt.expiration=86400000

#rate.limit.requests=10000000000
#rate.limit.duration=0